-- Set context
USE DATABASE GLOBAL_RETAIL_DB;
USE SCHEMA SALES;
USE WAREHOUSE "WAREHOUSE DEMO_WH";


-- Load transactions
COPY INTO TRANSACTIONS
FROM @S3_STAGE/
PATTERN = '.*Transaction_table_.*\.csv'
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);


-- Load customers
COPY INTO CUSTOMERS
FROM @S3_STAGE/
PATTERN = '.*Customers_table_.*\.csv'
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);


-- Load products
COPY INTO PRODUCTS
FROM @S3_STAGE/
PATTERN = '.*Products_table_.*\.csv'
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);


-- Load stores
COPY INTO STORES
FROM @S3_STAGE/
PATTERN = '.*Stores_table_.*\.csv'
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);