-- Set context
USE DATABASE GLOBAL_RETAIL_DB;
USE SCHEMA SALES;
USE WAREHOUSE "WAREHOUSE DEMO_WH";

-- Load transactions
COPY INTO TRANSACTIONS
FROM @S3_STAGE/Transaction_table_20250701_141027.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);


-- Load customers
COPY INTO CUSTOMERS
FROM @S3_STAGE/Customers_table_20250701_141027.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

-- Load products
COPY INTO PRODUCTS
FROM @S3_STAGE/Products_table_20250701_141027.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

-- Load stores
COPY INTO stores
FROM @S3_STAGE/Stores_table_20250701_141027.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
